#!/bin/bash
#
# Script to relyably mount network shares. Useful if the 
# target host is not always available on startup. For example
# if you have network mounts on your laptop.
#
# Version: 0.1
# Author: Reto Hugi (http://hugi.to/blog/)
# License: GPL v3 (http://www.gnu.org/licenses/gpl.html)
#
# Dependencies:
# - mountpoint
#
# Changelog:
# 2011-02-04 / Version 1.0 / initial release

    myMounts="/media/Tank-Backup /media/Tank-Transfer"
    myHost='192.168.1.11'
    
    ping -c 1 $myHost > /dev/null

    if [ "$?" -eq 0 ]; then
      for mount in $myMounts
      do
        echo 'mount: '+$mount
      done
      exit 0
    fi


    #mountpoint -q $1 || mount $1
    exit 0

