#!/bin/sh
#
# ipod-movie-converter is a (batch-)converter for your movies to an iPod readable
# format. ipod-movie-converter is a wrapper for pypodconv and lets you convert 
# movies with a right click within nautilus.
#
# Version: 1.0
# Author: Reto Hugi (http://hugi.to/blog/)
# License: GPL v3 (http://www.gnu.org/licenses/gpl.html)
#
# Dependencies:
# This script requires:
# - Zenity to display informations (install with "apt-get zenity")
# - pypodconv to convert movies
#
# Changelog:
# 2008-04-11 / Version 1.0 / initial release


LOGFILE=`mktemp -t ipod-movie-converter-tmp.XXXXXXX`
movies=`echo $*`

for movie in $movies; do
    
    filename=`echo $movie | sed 's_\(.*\)\.\(.*\)_\1_'`
    
    exec `pypodconv -i $movie -o $filename.mov > /dev/null`
    echo "* $movie one!" >> $LOGFILE
done

zenity --text-info --title="iPod Movie Converter" --filename=$LOGFILE --width=600 --height=400

rm -f $LOGFILE
exit 0
